export interface KeywordCategory {
  category: string;
  keywords: {
    term: string;
    type: 'hard' | 'soft';
    priority: 'high' | 'medium' | 'low';
    learnable: boolean;
    relatedTerms: string[];
  }[];
}

export const KEYWORD_DICT: KeywordCategory[] = [
  {
    category: '互联网',
    keywords: [
      { term: 'Python', type: 'hard', priority: 'high', learnable: true, relatedTerms: ['python', 'py'] },
      { term: 'Java', type: 'hard', priority: 'high', learnable: true, relatedTerms: ['java'] },
      { term: 'JavaScript', type: 'hard', priority: 'high', learnable: true, relatedTerms: ['js', 'javascript'] },
      { term: 'React', type: 'hard', priority: 'high', learnable: true, relatedTerms: ['react', 'reactjs'] },
      { term: 'Vue', type: 'hard', priority: 'high', learnable: true, relatedTerms: ['vue', 'vuejs'] },
      { term: 'Node.js', type: 'hard', priority: 'high', learnable: true, relatedTerms: ['node', 'nodejs'] },
      { term: 'MySQL', type: 'hard', priority: 'medium', learnable: true, relatedTerms: ['mysql', '数据库'] },
      { term: 'Redis', type: 'hard', priority: 'medium', learnable: true, relatedTerms: ['redis'] },
      { term: 'Docker', type: 'hard', priority: 'medium', learnable: true, relatedTerms: ['docker', '容器'] },
      { term: 'Git', type: 'hard', priority: 'medium', learnable: true, relatedTerms: ['git', '版本控制'] },
      { term: 'API', type: 'hard', priority: 'medium', learnable: true, relatedTerms: ['api', '接口'] },
      { term: '敏捷开发', type: 'soft', priority: 'medium', learnable: true, relatedTerms: ['敏捷', 'scrum'] },
      { term: '团队协作', type: 'soft', priority: 'high', learnable: false, relatedTerms: ['协作', '配合'] },
      { term: '问题排查', type: 'soft', priority: 'high', learnable: true, relatedTerms: ['调试', 'debug'] },
      { term: '文档编写', type: 'soft', priority: 'medium', learnable: true, relatedTerms: ['文档', 'wiki'] },
    ],
  },
  {
    category: '金融',
    keywords: [
      { term: '财务分析', type: 'hard', priority: 'high', learnable: true, relatedTerms: ['财务报表', '财报'] },
      { term: 'Excel', type: 'hard', priority: 'high', learnable: true, relatedTerms: ['excel', '表格'] },
      { term: '风险控制', type: 'hard', priority: 'high', learnable: true, relatedTerms: ['风控', '风险'] },
      { term: '数据分析', type: 'hard', priority: 'high', learnable: true, relatedTerms: ['数据分析', '数据处理'] },
      { term: '金融建模', type: 'hard', priority: 'high', learnable: true, relatedTerms: ['建模', 'financial model'] },
      { term: 'SQL', type: 'hard', priority: 'medium', learnable: true, relatedTerms: ['sql', '数据库查询'] },
      { term: 'PPT制作', type: 'hard', priority: 'medium', learnable: true, relatedTerms: ['ppt', '演示'] },
      { term: '客户沟通', type: 'soft', priority: 'high', learnable: true, relatedTerms: ['客户服务', '沟通'] },
      { term: '细心严谨', type: 'soft', priority: 'high', learnable: false, relatedTerms: ['认真', '细致'] },
      { term: '抗压能力', type: 'soft', priority: 'high', learnable: true, relatedTerms: ['能承受压力', '加班'] },
      { term: '学习能力', type: 'soft', priority: 'high', learnable: false, relatedTerms: ['快速学习', '接受新事物'] },
      { term: '团队合作', type: 'soft', priority: 'medium', learnable: false, relatedTerms: ['团队', '协作'] },
    ],
  },
  {
    category: '制造',
    keywords: [
      { term: 'CAD', type: 'hard', priority: 'high', learnable: true, relatedTerms: ['cad', '计算机辅助设计'] },
      { term: 'SolidWorks', type: 'hard', priority: 'high', learnable: true, relatedTerms: ['solidworks'] },
      { term: 'PLC', type: 'hard', priority: 'high', learnable: true, relatedTerms: ['plc', '可编程控制器'] },
      { term: '质量管理', type: 'hard', priority: 'high', learnable: true, relatedTerms: ['QC', 'qa', '质量控制'] },
      { term: '工艺流程', type: 'hard', priority: 'medium', learnable: true, relatedTerms: ['工艺', '流程'] },
      { term: '机械设计', type: 'hard', priority: 'medium', learnable: true, relatedTerms: ['机械', '设计'] },
      { term: '电子电路', type: 'hard', priority: 'medium', learnable: true, relatedTerms: ['电路', '电子'] },
      { term: '动手能力', type: 'soft', priority: 'high', learnable: true, relatedTerms: ['实操', '实践'] },
      { term: '安全意识', type: 'soft', priority: 'high', learnable: true, relatedTerms: ['安全', '安全生产'] },
      { term: '严谨细致', type: 'soft', priority: 'high', learnable: false, relatedTerms: ['严谨', '细致'] },
      { term: '问题解决', type: 'soft', priority: 'high', learnable: true, relatedTerms: ['解决问题', 'troubleshoot'] },
      { term: '团队协作', type: 'soft', priority: 'medium', learnable: false, relatedTerms: ['团队', '合作'] },
    ],
  },
  {
    category: '教育',
    keywords: [
      { term: '教学设计', type: 'hard', priority: 'high', learnable: true, relatedTerms: ['教案', '教学方案'] },
      { term: '课程开发', type: 'hard', priority: 'high', learnable: true, relatedTerms: ['课程设计', '教材编写'] },
      { term: '教学方法', type: 'hard', priority: 'high', learnable: true, relatedTerms: ['教学法', '教学技巧'] },
      { term: 'PPT制作', type: 'hard', priority: 'medium', learnable: true, relatedTerms: ['课件', '演示'] },
      { term: '班级管理', type: 'hard', priority: 'medium', learnable: true, relatedTerms: ['课堂管理', '班级'] },
      { term: '教育心理学', type: 'hard', priority: 'medium', learnable: true, relatedTerms: ['心理学', '教育心理'] },
      { term: '沟通表达', type: 'soft', priority: 'high', learnable: true, relatedTerms: ['表达能力', '讲解'] },
      { term: '耐心细致', type: 'soft', priority: 'high', learnable: false, relatedTerms: ['耐心', '细心'] },
      { term: '责任心', type: 'soft', priority: 'high', learnable: false, relatedTerms: ['责任感', '负责'] },
      { term: '亲和力', type: 'soft', priority: 'high', learnable: false, relatedTerms: ['亲切', '和善'] },
      { term: '学习能力', type: 'soft', priority: 'medium', learnable: false, relatedTerms: ['自我提升', '进修'] },
      { term: '创新思维', type: 'soft', priority: 'medium', learnable: true, relatedTerms: ['创新', '创意'] },
    ],
  },
  {
    category: '医疗',
    keywords: [
      { term: '临床诊断', type: 'hard', priority: 'high', learnable: true, relatedTerms: ['诊断', '临床'] },
      { term: '病历书写', type: 'hard', priority: 'high', learnable: true, relatedTerms: ['病历', '医疗文书'] },
      { term: '护理操作', type: 'hard', priority: 'high', learnable: true, relatedTerms: ['护理', '护理技术'] },
      { term: '医学知识', type: 'hard', priority: 'high', learnable: true, relatedTerms: ['医学', '医疗知识'] },
      { term: '药品知识', type: 'hard', priority: 'medium', learnable: true, relatedTerms: ['药学', '药品'] },
      { term: '医疗设备', type: 'hard', priority: 'medium', learnable: true, relatedTerms: ['医疗仪器', '设备操作'] },
      { term: '沟通能力', type: 'soft', priority: 'high', learnable: true, relatedTerms: ['医患沟通', '沟通'] },
      { term: '责任心', type: 'soft', priority: 'high', learnable: false, relatedTerms: ['责任感', '负责'] },
      { term: '细心严谨', type: 'soft', priority: 'high', learnable: false, relatedTerms: ['细致', '严谨'] },
      { term: '抗压能力', type: 'soft', priority: 'high', learnable: true, relatedTerms: ['压力承受', '应急'] },
      { term: '团队协作', type: 'soft', priority: 'high', learnable: false, relatedTerms: ['医护协作', '团队'] },
      { term: '学习能力', type: 'soft', priority: 'medium', learnable: false, relatedTerms: ['医学进修', '继续教育'] },
    ],
  },
  {
    category: '政府机关',
    keywords: [
      { term: '公文写作', type: 'hard', priority: 'high', learnable: true, relatedTerms: ['公文', '文稿撰写'] },
      { term: '政策研究', type: 'hard', priority: 'high', learnable: true, relatedTerms: ['政策分析', '政策解读'] },
      { term: '行政管理', type: 'hard', priority: 'high', learnable: true, relatedTerms: ['行政', '管理'] },
      { term: '组织协调', type: 'hard', priority: 'medium', learnable: true, relatedTerms: ['协调', '组织'] },
      { term: '办公软件', type: 'hard', priority: 'medium', learnable: true, relatedTerms: ['office', 'word', 'excel'] },
      { term: '档案管理', type: 'hard', priority: 'medium', learnable: true, relatedTerms: ['档案', '资料管理'] },
      { term: '政治素养', type: 'soft', priority: 'high', learnable: true, relatedTerms: ['政治觉悟', '思想政治'] },
      { term: '保密意识', type: 'soft', priority: 'high', learnable: true, relatedTerms: ['保密', '机密'] },
      { term: '责任心', type: 'soft', priority: 'high', learnable: false, relatedTerms: ['责任感', '负责'] },
      { term: '沟通协调', type: 'soft', priority: 'high', learnable: true, relatedTerms: ['沟通', '协调'] },
      { term: '严谨细致', type: 'soft', priority: 'high', learnable: false, relatedTerms: ['严谨', '细致'] },
      { term: '服务意识', type: 'soft', priority: 'medium', learnable: true, relatedTerms: ['服务', '为民服务'] },
    ],
  },
  {
    category: '咨询',
    keywords: [
      { term: '数据分析', type: 'hard', priority: 'high', learnable: true, relatedTerms: ['数据分析', '数据处理'] },
      { term: 'PPT制作', type: 'hard', priority: 'high', learnable: true, relatedTerms: ['ppt', 'slide'] },
      { term: '调研访谈', type: 'hard', priority: 'high', learnable: true, relatedTerms: ['调研', '访谈'] },
      { term: '战略规划', type: 'hard', priority: 'high', learnable: true, relatedTerms: ['战略', '规划'] },
      { term: 'Excel', type: 'hard', priority: 'high', learnable: true, relatedTerms: ['excel', '数据建模'] },
      { term: '项目管理', type: 'hard', priority: 'medium', learnable: true, relatedTerms: ['项目', '管理'] },
      { term: '商业思维', type: 'soft', priority: 'high', learnable: true, relatedTerms: ['商业敏锐度', 'business sense'] },
      { term: '沟通能力', type: 'soft', priority: 'high', learnable: true, relatedTerms: ['沟通', '表达'] },
      { term: '逻辑思维', type: 'soft', priority: 'high', learnable: true, relatedTerms: ['逻辑', '分析能力'] },
      { term: '抗压能力', type: 'soft', priority: 'high', learnable: true, relatedTerms: ['能承受压力', '高强度'] },
      { term: '快速学习', type: 'soft', priority: 'high', learnable: false, relatedTerms: ['学习能力', '快速上手'] },
      { term: '团队协作', type: 'soft', priority: 'medium', learnable: false, relatedTerms: ['团队', '合作'] },
    ],
  },
  {
    category: '快消',
    keywords: [
      { term: '市场调研', type: 'hard', priority: 'high', learnable: true, relatedTerms: ['调研', '市场分析'] },
      { term: '活动策划', type: 'hard', priority: 'high', learnable: true, relatedTerms: ['策划', '活动执行'] },
      { term: '销售技巧', type: 'hard', priority: 'high', learnable: true, relatedTerms: ['销售', '销售能力'] },
      { term: '客户关系', type: 'hard', priority: 'high', learnable: true, relatedTerms: ['客户维护', 'CRM'] },
      { term: '数据分析', type: 'hard', priority: 'medium', learnable: true, relatedTerms: ['数据', '销售分析'] },
      { term: '供应链', type: 'hard', priority: 'medium', learnable: true, relatedTerms: ['供应链管理', '物流'] },
      { term: '沟通能力', type: 'soft', priority: 'high', learnable: true, relatedTerms: ['沟通', '表达'] },
      { term: '执行力', type: 'soft', priority: 'high', learnable: true, relatedTerms: ['执行', '行动能力'] },
      { term: '抗压能力', type: 'soft', priority: 'high', learnable: true, relatedTerms: ['能承受压力', '高强度'] },
      { term: '结果导向', type: 'soft', priority: 'high', learnable: true, relatedTerms: ['目标导向', '业绩'] },
      { term: '团队协作', type: 'soft', priority: 'medium', learnable: false, relatedTerms: ['团队', '合作'] },
      { term: '创新思维', type: 'soft', priority: 'medium', learnable: true, relatedTerms: ['创新', '创意'] },
    ],
  },
];

export const STOP_WORDS: string[] = [
  '的', '了', '和', '是', '就', '都', '而', '及', '与', '在', '对', '于', '这', '那', '有', '我', '我们',
  '你', '你们', '他', '他们', '它', '它们', '这个', '那个', '什么', '怎么', '如何', '一些',
  '很多', '非常', '特别', '比较', '需要', '要求', '可以', '能够', '应该', '必须', '或者',
  '还是', '因为', '所以', '但是', '然而', '虽然', '如果', '假如', '只要', '除非', '不管',
  '尽管', '即使', '甚至', '而且', '此外', '另外', '同时', '然后', '最后', '总之', '招聘', '岗位',
  '职位', '职责', '负责', '工作', '经验', '学历', '专业', '优先', '优先考虑', '等等', '等',
  '任职', '资格', '条件', '具备', '熟悉', '掌握', '了解', '熟练', '精通', '擅长', '良好', '优秀',
];

export const SOFT_SKILL_BEHAVIORS: Record<string, string> = {
  '沟通能力': '能够清晰表达技术方案，在会议上有效传达进度和风险，能与非技术同事协作',
  '抗压能力': '能在deadline前保持工作质量，面对需求变更不情绪化，主动汇报困难而非隐瞒',
  '团队协作': '主动分享信息和经验，乐于帮助同事，能够接受不同意见，以团队目标为重',
  '学习能力': '主动关注行业新技术，快速掌握新工具，遇到问题能自主寻找解决方案',
  '责任心': '对工作结果负责，不推诿责任，主动跟进问题直到解决，即使加班也要完成任务',
  '逻辑思维': '分析问题有条理，能快速抓住核心，构建清晰的分析框架，推理过程严谨',
  '创新思维': '不满足现状，主动提出改进建议，敢于尝试新方法，从不同角度思考问题',
  '执行力': '接到任务快速行动，不拖延，遇到问题主动协调资源，确保按时交付',
  '问题解决': '遇到困难不放弃，能系统性排查问题，主动寻求资源支持，找到有效解决方案',
  '细心严谨': '关注细节，工作中反复检查，对数据准确性负责，发现问题及时纠正',
  '耐心细致': '面对复杂工作保持耐心，不厌其烦地处理细节，确保每个环节都到位',
  '亲和力': '待人友善，容易接近，善于倾听，能与不同性格的人建立良好关系',
  '保密意识': '严格遵守保密规定，不随意谈论敏感信息，妥善保管保密资料',
  '服务意识': '主动了解用户需求，积极解决用户问题，持续改进服务质量',
  '客户沟通': '能准确理解客户需求，清晰表达方案，妥善处理客户异议，维护客户关系',
  '结果导向': '以达成目标为核心，主动规划和推进工作，不达目的不罢休',
  '政治素养': '有正确的政治立场，了解国家政策，遵守法律法规',
  '商业思维': '关注市场趋势，理解商业模式，能从商业角度思考问题',
  '安全意识': '严格遵守安全规程，主动识别安全隐患，及时报告和处理安全问题',
  '动手能力': '能够实际操作设备和工具，喜欢实践，能把理论应用到实际工作中',
};
